services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python recreate_db.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString

databases:
  - name: fastapi-db
    databaseName: fastapi_db
    user: fastapi_user